In [2]:
import numpy as np


In [3]:
#np.array(elements)

In [6]:
import numpy as np
n1 = np.array([12,3,44,5,])
n1

array([12,  3, 44,  5])

In [7]:
zero_d=np.array(1)

In [11]:
zero_d

array(1)

In [15]:

zero_d.ndim

0

In [16]:
one_d= np.array([1,2,3,4])

In [17]:
one_d

array([1, 2, 3, 4])

In [19]:
one_d.ndim

1

In [20]:
n1=np.array(['chicken_burger','cheese_burger'])

In [21]:
n1

array(['chicken_burger', 'cheese_burger'], dtype='<U14')

In [24]:
two_d=np.array([[1,2,3,4],[6,7,8,9]])

In [25]:
two_d.ndim

2

In [26]:
two_d.size

8

In [27]:
n1 = np.array([[[1,2,3,4]]])

In [28]:
n1.ndim

3

In [29]:
n1.size

4

In [30]:
n1=np.array([[['chicken_burger','cheese_burger']]])

In [33]:
n1.ndim

3

In [34]:
n1

array([[['chicken_burger', 'cheese_burger']]], dtype='<U14')

In [36]:
n2=np.array([[1,2,3,4],[5,6,7,8]])

In [48]:
n2.shape

(1, 1, 4, 4)

In [19]:
n2=np.array([[[[1,2,3,4],[5,6,7,8],
 [12,13,14,15],[16,17,18,19]]]])

In [20]:
n2

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [12, 13, 14, 15],
         [16, 17, 18, 19]]]])

In [21]:
n2.ndim

4

In [46]:
n2.size

16

In [48]:
n2[0]

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19]]])

In [50]:
dict1={'a':1,'b':2}

In [51]:
for i in dict1:
    print(i)

a
b


In [5]:
import numpy as np
n1=np.array([[['a','b','c'],['a','b','c'],['a','b','c']]])

In [6]:
n1

array([[['a', 'b', 'c'],
        ['a', 'b', 'c'],
        ['a', 'b', 'c']]], dtype='<U1')

In [7]:
n1[0,2,2]

np.str_('c')

In [10]:
n1[0,2,1]

np.str_('b')

In [11]:
n1[0,2,0]

np.str_('a')

In [13]:
n1[0,1,1]

np.str_('b')

In [22]:
n1[0,1,2]

np.str_('c')

In [27]:
n1=np.array([[['a','b','c'],['a','b','c'],['a','b','c']]])
np.insert(n1,8,'r')

array(['a', 'b', 'c', 'a', 'b', 'c', 'a', 'b', 'r', 'c'], dtype='<U1')

In [35]:
n1=np.array([[['chicken_burger','cheese_burger']]])
np.insert(n1,1,'rakesh',axis=1)

array([[['chicken_burger', 'cheese_burger'],
        ['rakesh', 'rakesh']]], dtype='<U14')

In [39]:
n1=np.array([[['chicken_burger','cheese_burger']]])
np.insert(n1,0,'rakesh',axis=1)

array([[['rakesh', 'rakesh'],
        ['chicken_burger', 'cheese_burger']]], dtype='<U14')

In [41]:
np.append(n1,'rakesh')

array(['chicken_burger', 'cheese_burger', 'rakesh'], dtype='<U14')

In [45]:
np.add(n1,'lokesh')

array([[['chicken_burgerlokesh', 'cheese_burgerlokesh']]], dtype='<U20')

In [46]:
n1.shape

(1, 1, 2)

In [47]:
n2.shape

(1, 1, 4, 4)

In [49]:
n1=np.array([['chicken_burger','cheese_burger']])
n1

array([['chicken_burger', 'cheese_burger']], dtype='<U14')

In [50]:
n1.shape

(1, 2)

In [51]:
np.delete(n1,0)

array(['cheese_burger'], dtype='<U14')